Generate minimal OWL file using ASCT+B terms
hubmapconsortium/ccf-validation-tools pull request #112
Opened 2021-11-26 16:30 UTC by anitacaron

Fixes #111

2021-11-30 13:11 UTC, dosumis requested changes
See question

2021-11-30 13:11 UTC, dosumis commented on src/template_generation_tools.py
> +  all_edges = ug.construct_uberon(" ".join(list(terms_pairs.union(terms_ct_as))), ug.construct_all_edges)
Is this sufficient to generate all possible combinations of edges for testing in the where clause of construct_all_edges?  I'm wondering if this is why some edges are being dropped - e.g. in https://github.com/obophenotype/CCF_tools/issues/111#issuecomment-980091830


1. Some terms in the first graph are singletons but should be wired up, e.g.  
![image](https://user-images.githubusercontent.com/112839/143609688-fdbb7f53-49c1-4f46-bdf1-6c80ff12e61a.png)
should have a part_of relationship to 'kidney interstitum' - these terms are missing from graph 2
3. Some other edges missing, e.g. 'renal efferent arteriole' should be under 'kidney vasculature' and under 'renal corpuscle'

2021-11-30 17:28 UTC, dosumis commented on src/template_generation_tools.py
> +  all_edges = ug.construct_uberon(" ".join(list(terms_pairs.union(terms_ct_as))), ug.construct_all_edges)
Potential fix:
1. SELECT all triples from redundant graph with part_of in subject position and one of allowed OPs as predicate = set S
1. SELECT all triples from redundant graph with part_of in object position and one of allowed OPs as predicate = set  O
2. Generate intersection of sets S & O and use these to generate triples with SPARQL construct (as now)

2021-12-01 12:03 UTC, dosumis commented
Could you push the changes?  I'd like to have a look at the OWL file.

2022-07-06 14:54 UTC, diane-psc commented
Can this be merged? If not, can we archive it?

2022-07-20 09:12 UTC, closed without merging